# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/publishing-docker-images
# https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md
name: unit-testing
on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        perl: [ '5.34' ]
        #perl: [ '5.34', '5.32', '5.16.3' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: apt-get
        run:  |
          sudo apt-get update -y
          sudo apt-get install -y quicktree bioperl mash sqlite3 libgd-dev libsqlite3-dev libberkeleydb-perl libcdb-file-perl
      - name: cpanm installations
        run: cpanm --installdeps .
      - name: versions
        run:  |
          mash --version
          quicktree -v
          sqlite3 --version
      - run: perl -V
      - name: perl modules checks
        run: |
          for i in Bio::Tree::Statistics threads Bio::Matrix::IO Bio::Tree::DistanceFactory; do perl -M$i -e 'print "checking module $i";'; done
      - name: make test
        run: perl Makefile.PL && make && make test
